[package]
name = "wal3"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
opentelemetry = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
setsum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }

chroma-storage = { workspace = true }
chroma-error.workspace = true
chroma-config.workspace = true

[dev-dependencies]
guacamole = { version = "0.11", default-features = false }
proptest.workspace = true
rand.workspace = true
