[package]
name = "rust_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_bindings"
crate-type = ["cdylib"]

[dependencies]
async-trait = { workspace = true }
pyo3 = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
numpy = "0.23.0"

chroma-sqlite = { workspace = true }
chroma-frontend = { workspace = true }
chroma-sysdb = { workspace = true }
chroma-log = { workspace = true }
chroma-config = { workspace = true }
chroma-cache = { workspace = true }
chroma-system = { workspace = true }
chroma-types = { workspace = true }
