[package]
name = "spanner-migrations"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spanner_migration"
path = "src/main.rs"

[dependencies]
chroma-config = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
google-cloud-spanner = "0.33"
google-cloud-googleapis = { version = "0.16", features = ["spanner"] }
google-cloud-gax = "0.19"
rust-embed = { version = "8.0", features = ["include-exclude"] }
regex = "1.0"
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
figment = { version = "0.10", features = ["yaml", "env"] }
chroma-tracing = { workspace = true }
tonic = { workspace = true }
