[package]
name = "chroma-index"
version = "0.1.0"
edition = "2021"

[features]
default = []

[lib]
path = "src/lib.rs"

[[example]]
name = "sparse_vector_benchmark"
path = "examples/sparse_vector_benchmark.rs"

[dependencies]
rand = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
arrow = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
tantivy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
roaring = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
tempfile = { workspace = true }
base64 = { workspace = true }
bitpacking = { workspace = true }
bytemuck = { workspace = true }
itertools = { workspace = true }
hnswlib = { workspace = true }
opentelemetry = { version = "0.27.0", default-features = false, features = ["trace", "metrics"] }
simsimd = { workspace = true }
dashmap = { workspace = true }
usearch = { workspace = true }
faer = { workspace = true }
crossbeam = "0.8.4"

chroma-error = { workspace = true }
chroma-types = { workspace = true }
chroma-blockstore = { workspace = true }
chroma-cache = { workspace = true }
chroma-config = { workspace = true }
chroma-storage = { workspace = true }
chroma-tracing = { workspace = true }
chroma-distance = { workspace = true }

[dev-dependencies]
indicatif = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
sprs = { workspace = true }
chroma-benchmark = { workspace = true }
regex = { workspace = true }
rayon = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
hf-hub = { version = "0.3", features = ["tokio"] }
dirs = "5.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true }

[[bench]]
name = "full_text"
harness = false

[[bench]]
name = "literal"
harness = false

[[bench]]
name = "fts_regex"
harness = false

[[bench]]
name = "quantized_spann"
harness = false

[[bench]]
name = "fast_writer"
harness = false

[[bench]]
name = "binary_quantized"
harness = false
