[package]
name = "chroma-load"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

tracing = { workspace = true }
tracing-bunyan-formatter = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry_sdk = { workspace = true }

# Unlikely to be used in the workspace.
axum = "0.7"
chromadb = { git = "https://github.com/rescrv/chromadb-rs", rev = "4017daf7c5c601a095b5c509bfddabc6125e6616" }
guacamole = { version = "0.9", default-features = false }
tower-http = { version = "0.6.2", features = ["trace"] }
reqwest = { version = "0.12", features = ["json"] }
siphasher = "1.0.1"
