[package]
name = "chroma-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
fastrace = "0.7"
fastrace-opentelemetry = "0.8"
http = { version = "1", optional = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, optional = true }
tracing-bunyan-formatter = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
tracing.workspace = true

[features]
grpc = ["dep:tower", "dep:http"]
