blank_issues_enabled: true
contact_links:
  - name: ğŸ¤·ğŸ»â€â™€ï¸ Questions
    url: https://discord.com/invite/MMeYNTmh3x
    about: Interact with the Chroma community here by asking for help, discussing and more!
