[package]
name = "chroma-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = { workspace = true }
regex = { workspace = true }
rust-embed = { version = "8.5.0", features = ["include-exclude"] }
sea-query = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
pyo3 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
chroma-error = { workspace = true }
