[package]
name = "chroma-types"
version = "0.1.0"
authors = ["Max Isom <max@trychroma.com>", "Hammad Bashir hammad@trychroma.com", "Robert Escriva <robert@trychroma.com>"]
edition = "2021"
description = "Chroma-provided crate for internal types used in the Chroma API."
license = "Apache-2.0"
repository = "https://github.com/chroma-core/chroma"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
pyo3 = { workspace = true, optional = true }
validator = { workspace = true }
regex = { workspace = true }
regex-syntax = { workspace = true }
utoipa = { workspace = true }
sprs = { workspace = true }

# (Cross-crate testing dependencies)
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

chroma-error = { workspace = true, features = ["tonic", "validator"] }

[build-dependencies]
tonic-build = "0.10"

[features]
testing = ["dep:proptest", "dep:proptest-derive"]
