[package]
name = "chroma-types"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
pyo3 = { workspace = true, optional = true }
validator = { workspace = true }
regex = { workspace = true }
regex-syntax = { workspace = true }
utoipa = { workspace = true }

# (Cross-crate testing dependencies)
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

chroma-error = { workspace = true, features = ["tonic", "validator"] }
chroma-config = { workspace = true }

[build-dependencies]
tonic-build = "0.10"

[features]
testing = ["dep:proptest", "dep:proptest-derive"]
