# These kubernetes manifests are UNDER ACTIVE  DEVELOPMENT and are not yet ready for production use.
# They will be used for the upcoming distributed version of chroma. They are not even ready
# for testing yet. Please do not use them unless you are working on the distributed version of chroma.

apiVersion: chroma.cluster/v1
kind: MemberList
metadata:
  name: compaction-service-memberlist
  namespace: {{ .Values.namespace}}
spec:
  members:

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compaction-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - chroma.cluster
  resources:
  - memberlists
  verbs:
  - get
  - list
  - watch
  # TODO: FIX THIS LEAKY PERMISSION
  - create
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysdb-compaction-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compaction-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: sysdb-serviceaccount
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # Awkward name, but this lets the compaction-service-serviceaccount read
  # the compaction-service-memberlist.
  name: compaction-service-compaction-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compaction-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: compaction-service-serviceaccount
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compaction-service-memberlist-readerwriter-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compaction-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
