apiVersion: chroma.cluster/v1
kind: MemberList
metadata:
  name: garbage-collection-service-memberlist
  namespace: {{ .Values.namespace }}
spec:
  members:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garbage-collection-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
    - chroma.cluster
  resources:
    - memberlists
  namespace: {{ .Values.namespace }}
  verbs:
    - get
    - list
    - watch
    # TODO: FIX THIS LEAKY PERMISSION
    - create
    - update
    - patch
    - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysdb-garbage-collection-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garbage-collection-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sysdb-serviceaccount
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garbage-collection-service-garbage-collection-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garbage-collection-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: garbage-collector-serviceaccount
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garbage-collection-service-memberlist-readerwriter-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garbage-collection-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
