---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lease-watcher
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  namespace: {{ .Values.namespace }}
  verbs: ["get", "create", "watch", "update", "delete"]

---
