---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-watcher
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  namespace: {{ .Values.namespace }}
  verbs: ["get", "list", "watch"]

---
