# These kubernetes manifests are UNDER ACTIVE  DEVELOPMENT and are not yet ready for production use.
# They will be used for the upcoming distributed version of chroma. They are not even ready
# for testing yet. Please do not use them unless you are working on the distributed version of chroma.

apiVersion: chroma.cluster/v1
kind: MemberList
metadata:
  name: query-service-memberlist
  namespace: {{ .Values.namespace}}
spec:
  members:

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: query-service-memberlist-readerwriter
rules:
- apiGroups:
  - chroma.cluster
  resources:
  - memberlists
  verbs:
  - get
  - list
  - watch
  # TODO: FIX THIS LEAKY PERMISSION
  - create
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sysdb-query-service-memberlist-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: query-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: sysdb-serviceaccount
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # Awkward name, but this lets the query-service-serviceaccount read
  # the query-service-memberlist.
  name: query-service-query-service-memberlist-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: query-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: query-service-serviceaccount
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: query-service-memberlist-readerwriter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: query-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rust-frontend-service-query-service-memberlist-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: query-service-memberlist-readerwriter
subjects:
- kind: ServiceAccount
  name: rust-frontend-service-serviceaccount
  namespace: {{ .Values.namespace }}
