apiVersion: chroma.cluster/v1
kind: MemberList
metadata:
  name: rust-log-service-memberlist
  namespace: {{ .Values.namespace }}
spec:
  members:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rust-log-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
    - chroma.cluster
  resources:
    - memberlists
  namespace: {{ .Values.namespace }}
  verbs:
    - get
    - list
    - watch
    # TODO: FIX THIS LEAKY PERMISSION
    - create
    - update
    - patch
    - delete

---

# Allows the sysdb service to read and write to the memberlist
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysdb-rust-log-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rust-log-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sysdb-serviceaccount
  namespace: {{ .Values.namespace }}

---

# Allows the rust-frontend-service to read and write to the memberlist
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rust-frontend-service-rust-log-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rust-log-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: rust-frontend-service-serviceaccount
  namespace: {{ .Values.namespace }}
