{{- if gt (int .Values.rustSysdbService.replicaCount) 0 }}
{{if .Values.rustSysdbService.configuration}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-sysdb-service-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
{{  .Values.rustSysdbService.configuration | indent 4 }}
{{ end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-sysdb-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.rustSysdbService.replicaCount }}
  selector:
    matchLabels:
      app: rust-sysdb-service
  template:
    metadata:
      labels:
        app: rust-sysdb-service
    spec:
      volumes:
        {{if .Values.rustSysdbService.configuration}}
        - name: rust-sysdb-service-config
          configMap:
            name: rust-sysdb-service-config
        {{ end }}
      containers:
        - name: rust-sysdb-service
          image: "{{ .Values.rustSysdbService.image.repository }}:{{ .Values.rustSysdbService.image.tag }}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            periodSeconds: 1
            failureThreshold: 30 # 30 seconds to allow for initial startup
            grpc:
              port: 50051
              service: chroma.SysDB
          volumeMounts:
            {{if .Values.rustSysdbService.configuration}}
            - name: rust-sysdb-service-config
              mountPath: /config/
            {{ end }}
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: CONFIG_PATH
              value: "/config/config.yaml"
          resources:
            limits:
              cpu: {{ .Values.rustSysdbService.resources.limits.cpu }}
              memory: {{ .Values.rustSysdbService.resources.limits.memory }}
            requests:
              cpu: {{ .Values.rustSysdbService.resources.requests.cpu }}
              memory: {{ .Values.rustSysdbService.resources.requests.memory }}

---

apiVersion: v1
kind: Service
metadata:
  name: rust-sysdb-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
  selector:
    app: rust-sysdb-service
  type: ClusterIP
{{- end }}