name: Python Example with pytest
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run benchmark
        run: |
          cd chroma-server && python -m pip install -r requirements.txt && python -m pip install -r requirements_dev.txt
          cd ../examples/benchmarks
          pytest test_benchmarks.py --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: examples/benchmarks/output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          # alert-comment-cc-users: '@ktrz'

      # - name: Store benchmark result - separate results repo
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     name: Python Benchmark with pytest-benchmark
      #     tool: 'pytest'
      #     output-file-path: examples/benchmarks/output.json
      #     # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     auto-push: true
      #     # Show alert with commit comment on detecting possible performance regression
      #     alert-threshold: '200%'
      #     comment-on-alert: true
      #     fail-on-alert: true
      #     # alert-comment-cc-users: '@ktrz'
      #     gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'