name: ðŸ“¦ Release JavaScript client

on:
  push:
    tags:
      - 'js_release_[0-9]+\.[0-9]+\.[0-9]+'  # Match tags in the form js_release_X.Y.Z
      - 'js_release_alpha_[0-9]+\.[0-9]+\.[0-9]+'  # Match tags in the form js_release_alpha_X.Y.Z

jobs:
  release:
    strategy:
      matrix:
        registry: [ "https://registry.npmjs.org", "https://npm.pkg.github.com" ]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Check if tag matches the pattern
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/js_release_alpha_[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag matches the pattern js_release_alpha_X.Y.Z"
          echo "NPM_SCRIPT=release_alpha" >> "$GITHUB_ENV"
        elif [[ "${{ github.ref }}" =~ ^refs/tags/js_release_[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag matches the pattern js_release_X.Y.Z"
          echo "NPM_SCRIPT=release" >> "$GITHUB_ENV"
        else
          echo "Tag does not match the release tag pattern, exiting workflow"
          exit 1
        fi
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"
        registry-url: ${{ matrix.registry }}
    - name: Install dependencies
      run: npm install
      working-directory: ./clients/js/
    - name: Update package.json with organization scope
      if: matrix.registry == 'https://npm.pkg.github.com'
      run: |
        # needed to publish to GitHub packages only
        ORG_NAME="@chroma-core"
        PACKAGE_NAME=$(jq -r '.name' package.json)
        jq --arg org "$ORG_NAME" --arg name "$PACKAGE_NAME" '.name = "\($org)/\($name)"' package.json > tmp.$$.json && mv tmp.$$.json package.json
      working-directory: ./clients/js/
    - name: Test & publish
      run: npm run db:run && PORT=8001 npm run $NPM_SCRIPT
      working-directory: ./clients/js/
      env:
        NODE_AUTH_TOKEN: ${{ matrix.registry == 'https://registry.npmjs.org' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
